[package]
name = "sedimentree_sync_core"
version = "0.1.0"
edition.workspace = true

[dependencies]
futures = { workspace = true }
sedimentree_core = { path = "../sedimentree_core" }
serde = { version = "1.0" , features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }
