[package]
name = "sedimentree_sync_core"
version = "0.1.0"
edition = "2024"

[dependencies]
automerge.workspace = true
futures = "0.3.31"
sedimentree = "0.0.1"
serde = { version = "1.0" , features = ["derive"] }
tracing.workspace = true
