//! Golden-bytes tests pinning the wire codec to the legacy implementation.
//!
//! The expected hex vectors were generated by encoding these exact messages
//! with `legacy/subduction_core` (`MemorySigner` seeded with `[42u8; 32]`,
//! so the ed25519 signatures are deterministic). Any change to these bytes
//! is a wire-compatibility break — see `design/sans-io.md`.

use std::collections::BTreeSet;

use future_form::Sendable;
use sedimentree_core::{
    blob::{Blob, BlobMeta},
    crypto::fingerprint::{Fingerprint, FingerprintSeed},
    fragment::Fragment,
    id::SedimentreeId,
    loose_commit::{id::CommitId, LooseCommit},
    sedimentree::FingerprintSummary,
};
use subduction_crypto::{signed::Signed, signer::memory::MemorySigner};
use subduction_protocol::{
    peer_id::PeerId,
    remote_heads::RemoteHeads,
    wire::{
        BatchSyncRequest, BatchSyncResponse, DataRequestRejected, RemoveSubscriptions, RequestId,
        RequestedData, SyncDiff, SyncMessage, SyncResult,
    },
};
use testresult::TestResult;

fn from_hex(parts: &[&str]) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let joined: String = parts.concat();
    if !joined.len().is_multiple_of(2) {
        return Err("hex string must have even length".into());
    }
    (0..joined.len())
        .step_by(2)
        .map(|i| {
            let pair = joined.get(i..i + 2).ok_or("hex slice out of bounds")?;
            Ok(u8::from_str_radix(pair, 16)?)
        })
        .collect()
}

fn to_hex(bytes: &[u8]) -> Result<String, Box<dyn std::error::Error>> {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push(char::from_digit(u32::from(b >> 4), 16).ok_or("nibble out of range")?);
        s.push(char::from_digit(u32::from(b & 0xf), 16).ok_or("nibble out of range")?);
    }
    Ok(s)
}

/// Shared fixture matching the legacy golden dump exactly.
struct Fixture {
    id: SedimentreeId,
    blob: Blob,
    heads: RemoteHeads,
    signed_commit: Signed<LooseCommit>,
    signed_fragment: Signed<Fragment>,
    req_id: RequestId,
}

fn fixture() -> Fixture {
    let signer = MemorySigner::from_bytes(&[42u8; 32]);
    let id = SedimentreeId::new([1u8; 32]);
    let blob = Blob::new(vec![3u8; 16]);
    let heads = RemoteHeads {
        counter: 7,
        heads: vec![CommitId::new([0xAA; 32]), CommitId::new([0xBB; 32])],
    };

    let commit = LooseCommit::new(
        id,
        CommitId::new([0x42; 32]),
        BTreeSet::from([CommitId::new([0x41; 32])]),
        BlobMeta::new(&blob),
    );
    let signed_commit =
        futures::executor::block_on(Signed::seal::<Sendable, _>(&signer, commit)).into_signed();

    let fragment = Fragment::new(
        id,
        CommitId::new([2u8; 32]),
        BTreeSet::from([CommitId::new([3u8; 32])]),
        &[],
        BlobMeta::new(&blob),
    );
    let signed_fragment =
        futures::executor::block_on(Signed::seal::<Sendable, _>(&signer, fragment)).into_signed();

    let req_id = RequestId {
        requestor: PeerId::new([7u8; 32]),
        nonce: 99,
    };

    Fixture {
        id,
        blob,
        heads,
        signed_commit,
        signed_fragment,
        req_id,
    }
}

/// Check that `msg` encodes to exactly the legacy golden bytes, and that
/// the golden bytes decode back to `msg`.
fn assert_golden(msg: &SyncMessage, golden_hex: &[&str]) -> TestResult {
    let golden = from_hex(golden_hex)?;

    let encoded = msg.encode();
    assert_eq!(
        to_hex(&encoded)?,
        to_hex(&golden)?,
        "encoding differs from legacy golden bytes",
    );

    let decoded = SyncMessage::try_decode(&golden)?;
    assert_eq!(&decoded, msg, "golden bytes decoded to a different message");
    Ok(())
}

/// `loose_commit` golden bytes (hex), generated by the legacy implementation.
const GOLDEN_LOOSE_COMMIT: &[&str] = &[
    "53554d000000016c00010101010101010101010101010101010101010101010101010101010101010100000000000000",
    "0700000002aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbb",
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb53544300197f6b23e16c8532c6abc838facd5ea789be0c76b29203",
    "34039bfa8b3d368d61010101010101010101010101010101010101010101010101010101010101010142424242424242",
    "4242424242424242424242424242424242424242424242424223799507e9a195a789b458d7eeea43bb84b94a8b1ff9fe",
    "6f5320fd0ba3719d680110414141414141414141414141414141414141414141414141414141414141414182ebbefaaa",
    "c019bb3f5ada680c655d531bcbb72f244a4f026c8bc1871c24b7302b5d2a02cd7fdf6f652ddba4268fd6955b026bcec9",
    "dbc92973785a48e6a9a7031003030303030303030303030303030303",
];

/// `fragment` golden bytes (hex), generated by the legacy implementation.
const GOLDEN_FRAGMENT: &[&str] = &[
    "53554d000000016e01010101010101010101010101010101010101010101010101010101010101010100000000000000",
    "0700000002aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbb",
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb53544600197f6b23e16c8532c6abc838facd5ea789be0c76b29203",
    "34039bfa8b3d368d61010101010101010101010101010101010101010101010101010101010101010102020202020202",
    "0202020202020202020202020202020202020202020202020223799507e9a195a789b458d7eeea43bb84b94a8b1ff9fe",
    "6f5320fd0ba3719d68010000100303030303030303030303030303030303030303030303030303030303030303152c98",
    "ce408fa5bbe6fcf46b6bee2a99636a4589319c2ae0a99347a91259fc4b06adfc32154b0054e6f3c459a1e21fe6f46f8a",
    "ef0e76e4a4e66219adb9a176041003030303030303030303030303030303",
];

/// `batch_sync_request` golden bytes (hex), generated by the legacy implementation.
const GOLDEN_BATCH_SYNC_REQUEST: &[&str] = &[
    "53554d000000007e04010101010101010101010101010101010101010101010101010101010101010107070707070707",
    "07070707070707070707070707070707070707070707070707000000000000006301000000000000000b000000000000",
    "001600020001000000000000000100000000000000020000000000000003",
];

/// `batch_sync_response_ok` golden bytes (hex), generated by the legacy implementation.
const GOLDEN_BATCH_SYNC_RESPONSE_OK: &[&str] = &[
    "53554d00000002a605070707070707070707070707070707070707070707070707070707070707070700000000000000",
    "63010101010101010101010101010101010101010101010101010101010101010100000100010001000153544300197f",
    "6b23e16c8532c6abc838facd5ea789be0c76b2920334039bfa8b3d368d61010101010101010101010101010101010101",
    "010101010101010101010101010142424242424242424242424242424242424242424242424242424242424242422379",
    "9507e9a195a789b458d7eeea43bb84b94a8b1ff9fe6f5320fd0ba3719d68011041414141414141414141414141414141",
    "4141414141414141414141414141414182ebbefaaac019bb3f5ada680c655d531bcbb72f244a4f026c8bc1871c24b730",
    "2b5d2a02cd7fdf6f652ddba4268fd6955b026bcec9dbc92973785a48e6a9a70310030303030303030303030303030303",
    "0353544600197f6b23e16c8532c6abc838facd5ea789be0c76b2920334039bfa8b3d368d610101010101010101010101",
    "010101010101010101010101010101010101010101020202020202020202020202020202020202020202020202020202",
    "020202020223799507e9a195a789b458d7eeea43bb84b94a8b1ff9fe6f5320fd0ba3719d680100001003030303030303",
    "03030303030303030303030303030303030303030303030303152c98ce408fa5bbe6fcf46b6bee2a99636a4589319c2a",
    "e0a99347a91259fc4b06adfc32154b0054e6f3c459a1e21fe6f46f8aef0e76e4a4e66219adb9a1760410030303030303",
    "0303030303030303030300000000000000040000000000000005000000000000000700000002aaaaaaaaaaaaaaaaaaaa",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    "bbbbbbbbbbbb",
];

/// `batch_sync_response_not_found` golden bytes (hex), generated by the legacy implementation.
const GOLDEN_BATCH_SYNC_RESPONSE_NOT_FOUND: &[&str] = &[
    "53554d000000009e05070707070707070707070707070707070707070707070707070707070707070700000000000000",
    "63010101010101010101010101010101010101010101010101010101010101010101000000000000000700000002aaaa",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbb",
];

/// `batch_sync_response_unauthorized` golden bytes (hex), generated by the legacy implementation.
const GOLDEN_BATCH_SYNC_RESPONSE_UNAUTHORIZED: &[&str] = &[
    "53554d000000005e05070707070707070707070707070707070707070707070707070707070707070700000000000000",
    "63010101010101010101010101010101010101010101010101010101010101010102000000000000000000000000",
];

/// `remove_subscriptions` golden bytes (hex), generated by the legacy implementation.
const GOLDEN_REMOVE_SUBSCRIPTIONS: &[&str] = &[
    "53554d000000004b06000209090909090909090909090909090909090909090909090909090909090909090a0a0a0a0a",
    "0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a",
];

/// `data_request_rejected` golden bytes (hex), generated by the legacy implementation.
const GOLDEN_DATA_REQUEST_REJECTED: &[&str] =
    &["53554d0000000029070606060606060606060606060606060606060606060606060606060606060606"];

/// `heads_update` golden bytes (hex), generated by the legacy implementation.
const GOLDEN_HEADS_UPDATE: &[&str] = &[
    "53554d000000007508010101010101010101010101010101010101010101010101010101010101010100000000000000",
    "0700000002aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbb",
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
];

#[test]
fn loose_commit_matches_legacy() -> TestResult {
    let f = fixture();
    let msg = SyncMessage::LooseCommit {
        id: f.id,
        commit: f.signed_commit,
        blob: f.blob,
        sender_heads: f.heads,
    };
    assert_golden(&msg, GOLDEN_LOOSE_COMMIT)
}

#[test]
fn fragment_matches_legacy() -> TestResult {
    let f = fixture();
    let msg = SyncMessage::Fragment {
        id: f.id,
        fragment: f.signed_fragment,
        blob: f.blob,
        sender_heads: f.heads,
    };
    assert_golden(&msg, GOLDEN_FRAGMENT)
}

#[test]
fn batch_sync_request_matches_legacy() -> TestResult {
    let f = fixture();
    let msg = SyncMessage::BatchSyncRequest(BatchSyncRequest {
        id: f.id,
        req_id: f.req_id,
        fingerprint_summary: FingerprintSummary::new(
            FingerprintSeed::new(11, 22),
            BTreeSet::from([Fingerprint::from_u64(1), Fingerprint::from_u64(2)]),
            BTreeSet::from([Fingerprint::from_u64(3)]),
        ),
        subscribe: true,
    });
    assert_golden(&msg, GOLDEN_BATCH_SYNC_REQUEST)
}

#[test]
fn batch_sync_response_ok_matches_legacy() -> TestResult {
    let f = fixture();
    let msg = SyncMessage::BatchSyncResponse(BatchSyncResponse {
        req_id: f.req_id,
        id: f.id,
        result: SyncResult::Ok(SyncDiff {
            missing_commits: vec![(f.signed_commit, f.blob.clone())],
            missing_fragments: vec![(f.signed_fragment, f.blob)],
            requesting: RequestedData {
                commit_fingerprints: vec![Fingerprint::from_u64(4)],
                fragment_fingerprints: vec![Fingerprint::from_u64(5)],
            },
        }),
        responder_heads: f.heads,
    });
    assert_golden(&msg, GOLDEN_BATCH_SYNC_RESPONSE_OK)
}

#[test]
fn batch_sync_response_not_found_matches_legacy() -> TestResult {
    let f = fixture();
    let msg = SyncMessage::BatchSyncResponse(BatchSyncResponse {
        req_id: f.req_id,
        id: f.id,
        result: SyncResult::NotFound,
        responder_heads: f.heads,
    });
    assert_golden(&msg, GOLDEN_BATCH_SYNC_RESPONSE_NOT_FOUND)
}

#[test]
fn batch_sync_response_unauthorized_matches_legacy() -> TestResult {
    let f = fixture();
    let msg = SyncMessage::BatchSyncResponse(BatchSyncResponse {
        req_id: f.req_id,
        id: f.id,
        result: SyncResult::Unauthorized,
        responder_heads: RemoteHeads::default(),
    });
    assert_golden(&msg, GOLDEN_BATCH_SYNC_RESPONSE_UNAUTHORIZED)
}

#[test]
fn remove_subscriptions_matches_legacy() -> TestResult {
    let msg = SyncMessage::RemoveSubscriptions(RemoveSubscriptions {
        ids: vec![
            SedimentreeId::new([9u8; 32]),
            SedimentreeId::new([10u8; 32]),
        ],
    });
    assert_golden(&msg, GOLDEN_REMOVE_SUBSCRIPTIONS)
}

#[test]
fn data_request_rejected_matches_legacy() -> TestResult {
    let msg = SyncMessage::DataRequestRejected(DataRequestRejected {
        id: SedimentreeId::new([6u8; 32]),
    });
    assert_golden(&msg, GOLDEN_DATA_REQUEST_REJECTED)
}

#[test]
fn heads_update_matches_legacy() -> TestResult {
    let f = fixture();
    let msg = SyncMessage::HeadsUpdate {
        id: f.id,
        heads: f.heads,
    };
    assert_golden(&msg, GOLDEN_HEADS_UPDATE)
}

/// The indexed decoder's spans must slice out exactly each blob's bytes,
/// in documented order (commits before fragments for batch responses).
#[test]
fn indexed_decode_spans_locate_blobs() -> TestResult {
    let f = fixture();

    // Single-blob message.
    let msg = SyncMessage::LooseCommit {
        id: f.id,
        commit: f.signed_commit.clone(),
        blob: f.blob.clone(),
        sender_heads: f.heads.clone(),
    };
    let bytes = msg.encode();
    let (_decoded, spans) = SyncMessage::try_decode_indexed(&bytes)?;
    let [(off, len)] = spans[..] else {
        return Err("expected exactly one span".into());
    };
    assert_eq!(
        bytes.get(off as usize..(off + len) as usize),
        Some(f.blob.as_slice()),
        "span slices the exact blob bytes"
    );

    // Multi-blob response: commit blob first, then fragment blob.
    let commit_blob = f.blob.clone();
    let fragment_blob = Blob::new(vec![9u8; 24]);
    let fragment = {
        let meta = BlobMeta::new(&fragment_blob);
        let frag = Fragment::new(
            f.id,
            CommitId::new([0x33; 32]),
            std::collections::BTreeSet::new(),
            &[],
            meta,
        );
        let signer = MemorySigner::from_bytes(&[42u8; 32]);
        futures::executor::block_on(Signed::seal::<Sendable, _>(&signer, frag)).into_signed()
    };
    let msg = SyncMessage::BatchSyncResponse(BatchSyncResponse {
        req_id: f.req_id,
        id: f.id,
        result: SyncResult::Ok(SyncDiff {
            missing_commits: vec![(f.signed_commit, commit_blob.clone())],
            missing_fragments: vec![(fragment, fragment_blob.clone())],
            requesting: RequestedData::default(),
        }),
        responder_heads: f.heads,
    });
    let bytes = msg.encode();
    let (_decoded, spans) = SyncMessage::try_decode_indexed(&bytes)?;
    let [(c_off, c_len), (g_off, g_len)] = spans[..] else {
        return Err("expected exactly two spans".into());
    };
    assert_eq!(
        bytes.get(c_off as usize..(c_off + c_len) as usize),
        Some(commit_blob.as_slice()),
        "first span = commit blob"
    );
    assert_eq!(
        bytes.get(g_off as usize..(g_off + g_len) as usize),
        Some(fragment_blob.as_slice()),
        "second span = fragment blob"
    );
    Ok(())
}

/// Resolve scatter-gather parts against a fake blob table and compare
/// with plain `encode()` — the assembled bytes must be identical.
fn assemble(parts: &[subduction_protocol::blob_ref::Part], table: &[(u32, &[u8])]) -> Vec<u8> {
    use subduction_protocol::blob_ref::Part;
    let mut out = Vec::new();
    for part in parts {
        match part {
            Part::Bytes(b) => out.extend_from_slice(b),
            Part::Ref(r) => {
                let bytes = table
                    .iter()
                    .find(|(frame, _)| u64::from(*frame) == r.frame.as_u64())
                    .map_or(&[][..], |(_, b)| *b);
                out.extend_from_slice(bytes);
            }
        }
    }
    out
}

#[test]
fn scatter_gather_parts_match_plain_encoding() -> TestResult {
    use subduction_protocol::blob_ref::{BlobRef, FrameId};
    let f = fixture();
    let blob_len = u32::try_from(f.blob.as_slice().len())?;

    // Single-item message.
    let blob_ref = BlobRef {
        frame: FrameId::new(1),
        offset: 0,
        len: blob_len,
    };
    let parts =
        subduction_protocol::wire::loose_commit_parts(f.id, &f.signed_commit, &f.heads, blob_ref);
    let assembled = assemble(&parts, &[(1, f.blob.as_slice())]);
    let plain = SyncMessage::LooseCommit {
        id: f.id,
        commit: f.signed_commit.clone(),
        blob: f.blob.clone(),
        sender_heads: f.heads.clone(),
    }
    .encode();
    assert_eq!(assembled, plain, "loose-commit parts assemble identically");

    // Batch response with one commit and one fragment blob.
    let commit_blob = f.blob.clone();
    let fragment_blob = Blob::new(vec![5u8; 32]);
    let fragment = {
        let meta = BlobMeta::new(&fragment_blob);
        let frag = Fragment::new(
            f.id,
            CommitId::new([0x44; 32]),
            std::collections::BTreeSet::new(),
            &[],
            meta,
        );
        let signer = MemorySigner::from_bytes(&[42u8; 32]);
        futures::executor::block_on(Signed::seal::<Sendable, _>(&signer, frag)).into_signed()
    };
    let requesting = RequestedData {
        commit_fingerprints: vec![sedimentree_core::crypto::fingerprint::Fingerprint::from_u64(4)],
        fragment_fingerprints: vec![],
    };
    let c_ref = BlobRef {
        frame: FrameId::new(2),
        offset: 0,
        len: u32::try_from(commit_blob.as_slice().len())?,
    };
    let g_ref = BlobRef {
        frame: FrameId::new(3),
        offset: 0,
        len: u32::try_from(fragment_blob.as_slice().len())?,
    };
    let parts = subduction_protocol::wire::batch_sync_response_parts(
        f.req_id,
        f.id,
        &[(f.signed_commit.clone(), c_ref)],
        &[(fragment.clone(), g_ref)],
        &requesting,
        &f.heads,
    );
    let assembled = assemble(
        &parts,
        &[(2, commit_blob.as_slice()), (3, fragment_blob.as_slice())],
    );
    let plain = SyncMessage::BatchSyncResponse(BatchSyncResponse {
        req_id: f.req_id,
        id: f.id,
        result: SyncResult::Ok(SyncDiff {
            missing_commits: vec![(f.signed_commit, commit_blob)],
            missing_fragments: vec![(fragment, fragment_blob)],
            requesting,
        }),
        responder_heads: f.heads,
    })
    .encode();
    assert_eq!(
        assembled, plain,
        "batch-response parts assemble identically"
    );
    Ok(())
}
