//! Shared fixtures for integration tests.
//!
//! Every test that drives a node needs the same handful of things: a
//! deterministic signer, a blob, a commit id, a running node, a connected
//! pair, and a way to wait for state to settle. Each test file used to carry
//! its own copy, which meant a dozen slightly different `make_node`s and no
//! single place to fix a pattern once it turned out to be wrong.
//!
//! Connection-level mocks ([`ChannelTransport`], [`ChannelMockConnection`],
//! the timeouts and spawners) live in
//! [`connection::test_utils`](crate::connection::test_utils); this module is
//! the layer above them.
//!
//! Property tests should prefer generated values — `Blob` implements
//! [`arbitrary::Arbitrary`], and a signer comes from generated bytes via
//! `MemorySigner::from_bytes` — and reach for the seeded helpers here only
//! when a test reads better with a fixed, nameable commit.

#![allow(
    clippy::expect_used,
    reason = "fixtures panic on impossible setup failures; tests are the caller"
)]

use alloc::{sync::Arc, vec::Vec};
use core::time::Duration;

use future_form::Sendable;
use sedimentree_core::{
    blob::Blob, depth::CountLeadingZeroBytes, id::SedimentreeId, loose_commit::id::CommitId,
    test_utils::commit_id_with_depth,
};
use subduction_crypto::signer::memory::MemorySigner;

use crate::{
    authenticated::{Authenticated, Direction},
    connection::{
        message::SyncMessage,
        test_utils::{ChannelTransport, InstantTimeout, PausableChannelTransport, TokioSpawn},
    },
    handler::sync::SyncHandler,
    peer::id::PeerId,
    policy::open::OpenPolicy,
    storage::memory::MemoryStorage,
    subduction::{Subduction, builder::SubductionBuilder},
    timeout::Timeout,
    transport::message::MessageTransport,
};

/// How long [`wait_until`] polls before giving up.
pub const WAIT_TIMEOUT: Duration = Duration::from_secs(5);

/// A node built on the in-process channel transport.
pub type ChannelConn = MessageTransport<ChannelTransport>;

/// A running test node over connection type `Conn`, with timer `Timer`.
pub type TestNode<Conn, Timer> = Arc<
    Subduction<
        'static,
        Sendable,
        MemoryStorage,
        Conn,
        SyncHandler<Sendable, MemoryStorage, Conn, OpenPolicy, CountLeadingZeroBytes, TokioSpawn>,
        OpenPolicy,
        MemorySigner,
        Timer,
        TokioSpawn,
    >,
>;

/// A deterministic signer for `seed`.
#[must_use]
pub fn make_signer(seed: u8) -> MemorySigner {
    MemorySigner::from_bytes(&[seed; 32])
}

/// The [`PeerId`] [`make_signer`] produces for `seed`.
#[must_use]
pub fn make_peer_id(seed: u8) -> PeerId {
    PeerId::from(make_signer(seed).verifying_key())
}

/// A 64-byte blob whose contents are determined by `seed`.
#[must_use]
pub fn make_blob(seed: u8) -> Blob {
    Blob::new((0..64).map(|i| seed.wrapping_add(i)).collect::<Vec<u8>>())
}

/// A depth-zero commit id nicknamed by `seed`.
///
/// A `u8` rather than the full `[u8; 32]`, because a full array would make
/// this [`CommitId::new`]: the point is a short nickname a test can repeat and
/// a failure message can name. Depth zero keeps ids off fragment boundaries,
/// which is what a test wants unless it says otherwise 2014 use
/// [`commit_id_with_depth`] directly when it does.
#[must_use]
pub fn make_head(seed: u8) -> CommitId {
    commit_id_with_depth(0, seed)
}

/// A sedimentree id of all `seed` bytes.
#[must_use]
pub const fn make_tree_id(seed: u8) -> SedimentreeId {
    SedimentreeId::new([seed; 32])
}

/// Poll `cond` until it holds or [`WAIT_TIMEOUT`] elapses.
///
/// Prefer this to sleeping: a sleep before a *negative* assertion passes for
/// the wrong reason when the machine is slow, whereas polling a positive
/// witness says when the thing under test has actually happened.
pub async fn wait_until<F, Fut>(mut cond: F) -> bool
where
    F: FnMut() -> Fut,
    Fut: core::future::Future<Output = bool>,
{
    let deadline = tokio::time::Instant::now() + WAIT_TIMEOUT;
    loop {
        if cond().await {
            return true;
        }

        if tokio::time::Instant::now() >= deadline {
            return false;
        }

        tokio::time::sleep(Duration::from_millis(5)).await;
    }
}

/// Build a node for `seed` and spawn its listener and connection manager.
///
/// Returns the node and its [`PeerId`], which tests almost always need
/// together.
#[must_use]
pub fn spawn_node<Conn, Timer>(seed: u8, timer: Timer) -> (TestNode<Conn, Timer>, PeerId)
where
    Conn: crate::connection::Connection<Sendable, SyncMessage>
        + PartialEq
        + Clone
        + core::fmt::Debug
        + Send
        + Sync
        + 'static,
    Conn::SendError: Send + Sync + 'static,
    Conn::RecvError: Send + Sync + 'static,
    Conn::DisconnectionError: Send + Sync + 'static,
    Timer: Timeout<Sendable> + Clone + Send + Sync + 'static,
{
    let signer = make_signer(seed);
    let peer = PeerId::from(signer.verifying_key());

    let (node, _handler, listener, manager) = SubductionBuilder::new()
        .signer(signer)
        .storage(MemoryStorage::new(), Arc::new(OpenPolicy))
        .spawner(TokioSpawn)
        .timer(timer)
        .build::<Sendable, Conn>();

    tokio::spawn(listener);
    tokio::spawn(manager);

    (node, peer)
}

/// [`spawn_node`] on the channel transport with an instant timer — the shape
/// most tests want.
#[must_use]
pub fn spawn_channel_node(seed: u8) -> (TestNode<ChannelConn, InstantTimeout>, PeerId) {
    spawn_node(seed, InstantTimeout)
}

/// Connect two channel-transport nodes, recording `dialer` as the side that
/// dialed.
///
/// The direction is what [`Subduction::propagate_subscription`] reads to
/// decide where a subscription may be forwarded, so tests that care about
/// topology must set it deliberately rather than let both ends look alike.
///
/// # Panics
///
/// Panics if either node refuses the connection.
pub async fn dial<Timer: Timeout<Sendable> + Clone + Send + Sync + 'static>(
    dialer: &TestNode<ChannelConn, Timer>,
    dialer_peer: PeerId,
    target: &TestNode<ChannelConn, Timer>,
    target_peer: PeerId,
) {
    let (out, inbound) = ChannelTransport::pair();

    dialer
        .add_connection(Authenticated::new_for_test(
            MessageTransport::new(out),
            target_peer,
            Direction::Dialed,
        ))
        .await
        .expect("dialer should accept the connection");

    target
        .add_connection(Authenticated::new_for_test(
            MessageTransport::new(inbound),
            dialer_peer,
            Direction::Accepted,
        ))
        .await
        .expect("target should accept the connection");
}

/// A node on the pausable transport, for tests that wedge one side's writes.
pub type PausableConn = MessageTransport<PausableChannelTransport>;

/// [`dial`] over [`PausableChannelTransport`], returning both ends so a test
/// can pause the side it wants wedged.
///
/// # Panics
///
/// Panics if either node refuses the connection.
pub async fn dial_pausable<Timer: Timeout<Sendable> + Clone + Send + Sync + 'static>(
    dialer: &TestNode<PausableConn, Timer>,
    dialer_peer: PeerId,
    target: &TestNode<PausableConn, Timer>,
    target_peer: PeerId,
) -> (PausableChannelTransport, PausableChannelTransport) {
    let (out, inbound) = PausableChannelTransport::pair();

    dialer
        .add_connection(Authenticated::new_for_test(
            MessageTransport::new(out.clone()),
            target_peer,
            Direction::Dialed,
        ))
        .await
        .expect("dialer should accept the connection");

    target
        .add_connection(Authenticated::new_for_test(
            MessageTransport::new(inbound.clone()),
            dialer_peer,
            Direction::Accepted,
        ))
        .await
        .expect("target should accept the connection");

    (out, inbound)
}
